###################### Filebeat Configuration #########################

filebeat.inputs:

  # Nginx logs
  - type: filestream
    enabled: true
    id: nginx-logs
    paths:
      - /var/log/nginx/*.log
    tags: ["nginx"]
    # Allow smaller files to be ingested
    prospector.scanner.fingerprint.length: 16
    prospector.scanner.fingerprint.offset: 0
    ignore_older: 0s  # Optional: don't ignore new small files

  # Fail2ban logs
  - type: filestream
    enabled: true
    id: fail2ban-logs
    paths:
      - /var/log/fail2ban.log
    tags: ["fail2ban"]
    prospector.scanner.fingerprint.length: 16
    prospector.scanner.fingerprint.offset: 0
    ignore_older: 0s

# Disable modules entirely to remove module-related errors
filebeat.config.modules:
  path: /etc/filebeat/modules.d/*.yml
  reload.enabled: false

filebeat.modules: []

# Output to Logstash
output.elasticsearch:
  enabled: false

output.logstash:
  hosts: ["192.168.121.1:5044"]  # Ensure default Logstash port
  ssl.enabled: false

# Add metadata to each event
processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~

# Logging configuration
logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644
